### ISSUE TITLE
gcc 5.4.0 compilation error in formmanager plugin

### ISSUE THREAD

**Issue by jeromecc** [FreeHealth/freehealth#62]
formmanager plugin doesn't compile on gcc 5.4.0 (Ubuntu 16.04 Xenial)

/home/elkcloner/git/freehealth/build/Qt5_linux-gpp-64/FreeHealth/FormManager_debug/.obj/unix/formcontextualwidgetmanager.o: In function `Form::Internal::FormContextualWidgetManager::FormContextualWidgetManager(QObject*)':
/home/elkcloner/git/freehealth/plugins/formmanagerplugin/formcontextualwidgetmanager.cpp:131: undefined reference to `vtable for Form::Internal::FormContextualWidgetManager'
/home/elkcloner/git/freehealth/build/Qt5_linux-gpp-64/FreeHealth/FormManager_debug/.obj/unix/formcontextualwidgetmanager.o: In function `Form::Internal::FormContextualWidgetManager::~FormContextualWidgetManager()':
/home/elkcloner/git/freehealth/plugins/formmanagerplugin/formcontextualwidgetmanager.cpp:138: undefined reference to `vtable for Form::Internal::FormContextualWidgetManager'
/home/elkcloner/git/freehealth/build/Qt5_linux-gpp-64/FreeHealth/FormManager_debug/.obj/unix/formcontextualwidgetmanager.o: In function `Form::Internal::FormActionHandler::FormActionHandler(QObject*)':
/home/elkcloner/git/freehealth/plugins/formmanagerplugin/formcontextualwidgetmanager.cpp:210: undefined reference to `vtable for Form::Internal::FormActionHandler'
/home/elkcloner/git/freehealth/build/Qt5_linux-gpp-64/FreeHealth/FormManager_debug/.obj/unix/formcontextualwidgetmanager.o: In function `Form::Internal::FormActionHandler::~FormActionHandler()':
/home/elkcloner/git/freehealth/plugins/formmanagerplugin/formcontextualwidgetmanager.h:46: undefined reference to `vtable for Form::Internal::FormActionHandler'
/home/elkcloner/git/freehealth/build/Qt5_linux-gpp-64/FreeHealth/FormManager_debug/.obj/unix/formviewdelegate.o: In function `Form::Internal::FormViewDelegate::FormViewDelegate(QObject*)':
/home/elkcloner/git/freehealth/plugins/formmanagerplugin/formviewdelegate.cpp:49: undefined reference to `vtable for Form::Internal::FormViewDelegate'
/home/elkcloner/git/freehealth/build/Qt5_linux-gpp-64/FreeHealth/FormManager_debug/.obj/unix/patientformitemdatawrapper.o: In function `Form::PatientFormItemDataWrapper::PatientFormItemDataWrapper(QObject*)':
/home/elkcloner/git/freehealth/plugins/formmanagerplugin/patientformitemdatawrapper.cpp:199: undefined reference to `vtable for Form::PatientFormItemDataWrapper'
/home/elkcloner/git/freehealth/build/Qt5_linux-gpp-64/FreeHealth/FormManager_debug/.obj/unix/patientformitemdatawrapper.o: In function `Form::PatientFormItemDataWrapper::~PatientFormItemDataWrapper()':
/home/elkcloner/git/freehealth/plugins/formmanagerplugin/patientformitemdatawrapper.cpp:205: undefined reference to `vtable for Form::PatientFormItemDataWrapper'
/home/elkcloner/git/freehealth/build/Qt5_linux-gpp-64/FreeHealth/FormManager_debug/.obj/unix/formexporter.o: In function `Form::Internal::FormExporter::FormExporter(bool, QObject*)':
/home/elkcloner/git/freehealth/plugins/formmanagerplugin/formexporter.cpp:270: undefined reference to `vtable for Form::Internal::FormExporter'
/home/elkcloner/git/freehealth/build/Qt5_linux-gpp-64/FreeHealth/FormManager_debug/.obj/unix/formexporter.o: In function `Form::Internal::FormExporter::~FormExporter()':
/home/elkcloner/git/freehealth/plugins/formmanagerplugin/formexporter.cpp:277: undefined reference to `vtable for Form::Internal::FormExporter'
/home/elkcloner/git/freehealth/build/Qt5_linux-gpp-64/FreeHealth/FormManager_debug/.obj/unix/formexporter.o: In function `Form::Internal::FormExporter::tr(char const*, char const*, int)':
/home/elkcloner/git/freehealth/plugins/formmanagerplugin/formexporter.h:48: undefined reference to `Form::Internal::FormExporter::staticMetaObject'
collect2: error: ld returned 1 exit status

**Comment by jeromecc** [comment]
a few destructors were not virtual or were missing
fixed with commit 7a621ca1e4ac6062c78740976345baf699da056a
